/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.yefo.SimpleWebServer;

import java.io.IOException;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.Parent;
import javafx.scene.control.Label;

import javafx.stage.Stage;

import javafx.fxml.FXMLLoader;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }
    
    @Override
    public void start(Stage primaryStage) throws IOException {
        Parent root = FXMLLoader.load(getClass().getResource("/id/yefo/SimpleWebServer/MainView.fxml"));
        Scene scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Yefo's Simple Web Server");
        primaryStage.show();
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        launch(args);
    }
}
